### ISSUE TITLE
Can't scale up Operator

### ISSUE THREAD

**Issue by eumel8** [rancher/helm-project-operator#42]
I installed Helm Project Operator with the provided Helm chart. With handle 20-30+ projects the Operator needs many recources, died with Oomkilled, and has not the right performance. The idea was to scale up the deployment, but the [replicaset is hard coded to 1](https://github.com/rancher/helm-project-operator/blob/main/charts/helm-project-operator/templates/deployment.yaml#L9). This should be configurable, also to get more availability.

**Comment by aiyengar2** [comment]
@eumel8 regarding the number of replicas, I would be **in favor of providing that as a configurable option** (cc: @geethub97 @bashofmann). There are minor benefits to doing this (primarily that if one pod runs into an error, such as a panic, another pod can take over with less downtime since it's already been initialized).

However, regarding the **underlying issue** you are referring to (i.e. you want multiple versions of the operator to work together to manage all the projects), this would not alleviate your issue.

The reason why is that Helm Project Operator attempts to acquire a lock so that only one version of it running within the cluster will be running controllers at a given time, see https://github.com/rancher/helm-project-operator/blob/96ff247e12d8e5d2199e4476c94a55c6159469c3/pkg/controllers/controllers.go#L206-L211

**Comment by eumel8** [comment]
@aiyengar2 thanks for explanation. I know the logic of an Operator and yes, a replica can only cover errors of the main pod. So I'm fine with an configuration option `replicas` in Helm. Would be Operations a little bit safer.

**Comment by aiyengar2** [comment]
Sounds good. We can resolve this issue on adding the ability to configure replicas in Helm Project Operator / Prometheus Federator Helm chart and use https://github.com/rancher/helm-project-operator/issues/3 to continue to track the other scaling feature.

cc: @geethub97 @MKlimuszka
